# Generated by Django 5.1.4 on 2025-01-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='address',
            new_name='position',
        ),
    ]
